title: Gradient Explosion
logo: "" # You can add own logo image.
description: Эссе и объяснение концептов машинного обучения.
baseurl: "/gradient-explosion" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Anna Kozlova
  bio: Меня зовут Аня и я NLU-инженер. Здесь объясняю концепты машинного обучения простыми словами.

# Contact links
email: noriel266@gmail.com # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Gradient Explosion
hero-subtitle: Машинное обучение на салфетке
hero-image: images/aurora.jpg

# Footer
footer-image: images/aurora.jpg

# Comment Section (Disqus)
disqus-identifier: anna-gradients-explosion

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: ""

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed